name: Continuous Integration

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run lint
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run unit
        env:
          CI: true

  dependabot:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: 'gh pr merge --auto --rebase "$PULL_REQUEST"'
        env:
          PULL_REQUEST: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
